# Generated by Django 6.1 on 2026-08-21 10:15

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('assigned_unit', models.CharField(blank=True, choices=[('SOP_A', 'SOP A'), ('SOP_B', 'SOP B'), ('SOP_C', 'SOP C'), ('SOP_D', 'SOP D'), ('G_SOP', 'G SOP'), ('C_PACKING', 'C.Packing'), ('DCP', 'DCP'), ('PA', 'PA'), ('SA', 'SA'), ('GCC1', 'GCC1'), ('GCC2', 'GCC2'), ('LOADING', 'Loading')], max_length=20, null=True, verbose_name='الوحدة المسند إليها')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ShiftEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(choices=[('SOP_A', 'SOP A'), ('SOP_B', 'SOP B'), ('SOP_C', 'SOP C'), ('SOP_D', 'SOP D'), ('G_SOP', 'G SOP'), ('C_PACKING', 'C.Packing'), ('DCP', 'DCP'), ('PA', 'PA'), ('SA', 'SA'), ('GCC1', 'GCC1'), ('GCC2', 'GCC2'), ('LOADING', 'Loading')], max_length=20, verbose_name='الوحدة')),
                ('entry_date', models.DateField(verbose_name='التاريخ')),
                ('shift', models.CharField(choices=[('SHIFT_1', 'الوردية الأولى'), ('SHIFT_2', 'الوردية الثانية'), ('SHIFT_3', 'الوردية الثالثة')], max_length=10, verbose_name='الوردية')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الإدخال')),
                ('general_notes', models.TextField(blank=True, verbose_name='ملاحظات عامة')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_entries', to=settings.AUTH_USER_MODEL, verbose_name='أدخلها')),
            ],
            options={
                'ordering': ['entry_date', 'unit', 'shift'],
            },
        ),
        migrations.CreateModel(
            name='SALineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jc', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='JC')),
                ('shift_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sa_line_items', to='qc_report.shiftentry')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PALineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jc_43', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='JC 43')),
                ('jc_62', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='JC 62')),
                ('cube_43', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cube 43')),
                ('cube_61', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cube 61')),
                ('shift_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pa_line_items', to='qc_report.shiftentry')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='LoadingLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('SOP', 'SOP'), ('GSOP', 'GSOP'), ('GCC', 'GCC'), ('DCP', 'DCP'), ('PA', 'PA'), ('SA', 'SA'), ('HCL', 'HCL')], max_length=10, verbose_name='نوع المنتج')),
                ('exp', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='EXP')),
                ('dom', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='DOM')),
                ('shift_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loading_line_items', to='qc_report.shiftentry')),
            ],
            options={
                'ordering': ['product_type'],
            },
        ),
        migrations.CreateModel(
            name='GCCLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_type', models.CharField(choices=[('B_B', 'B.B'), ('S_B', 'S.B')], max_length=10, verbose_name='نوع العبوة')),
                ('green', models.PositiveIntegerField(default=0, verbose_name='أخضر')),
                ('yellow', models.PositiveIntegerField(default=0, verbose_name='أصفر')),
                ('white', models.PositiveIntegerField(default=0, verbose_name='أبيض')),
                ('blue', models.PositiveIntegerField(default=0, verbose_name='أزرق')),
                ('nc', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='NC')),
                ('defect_reason', models.CharField(blank=True, max_length=100, verbose_name='سبب العيب')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('shift_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gcc_line_items', to='qc_report.shiftentry')),
            ],
            options={
                'ordering': ['package_type'],
            },
        ),
        migrations.CreateModel(
            name='DCPWhiteQuality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('im', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='IM')),
                ('over', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Over')),
                ('color', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Color')),
                ('p2o5', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='P2O5')),
                ('mc', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='MC')),
                ('nc_count', models.PositiveIntegerField(default=0, verbose_name='عدد NC')),
                ('shift_entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dcp_white_quality', to='qc_report.shiftentry')),
            ],
        ),
        migrations.CreateModel(
            name='DCPUnderTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الكمية')),
                ('shift_entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dcp_under_test', to='qc_report.shiftentry')),
            ],
        ),
        migrations.CreateModel(
            name='DCPSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bb_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='B.B')),
                ('as_sb_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='AS S.B')),
                ('total_1', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='TOTAL (1)')),
                ('total_2', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='TOTAL (2)')),
                ('lab_test_count', models.PositiveIntegerField(default=0, verbose_name='اختبار معمل')),
                ('yesterday_test_count', models.PositiveIntegerField(default=0, verbose_name='اختبار امس')),
                ('unlabeled_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('shift_entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dcp_summary', to='qc_report.shiftentry')),
            ],
        ),
        migrations.CreateModel(
            name='DCPRework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='اجمالي')),
                ('green_yellow', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='اخضر واصفر')),
                ('yellow', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='اصفر')),
                ('green', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='اخضر')),
                ('shift_entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dcp_rework', to='qc_report.shiftentry')),
            ],
        ),
        migrations.CreateModel(
            name='DCPColorGrading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('TOTAL', 'الإجمالي'), ('EX_SB', 'EX S.B'), ('DOM_SB', 'DOM S.B'), ('SB_WHITE', 'S.B White')], max_length=10, verbose_name='الفئة')),
                ('green', models.PositiveIntegerField(default=0, verbose_name='أخضر')),
                ('yellow', models.PositiveIntegerField(default=0, verbose_name='أصفر')),
                ('green_yellow', models.PositiveIntegerField(default=0, verbose_name='أخضر وأصفر')),
                ('blue', models.PositiveIntegerField(default=0, verbose_name='أزرق')),
                ('white', models.PositiveIntegerField(default=0, verbose_name='أبيض')),
                ('red', models.PositiveIntegerField(default=0, verbose_name='أحمر')),
                ('shift_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dcp_color_gradings', to='qc_report.shiftentry')),
            ],
            options={
                'ordering': ['category'],
            },
        ),
        migrations.CreateModel(
            name='SOPLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('S_B', 'S.B'), ('B_B', 'B.B'), ('BULK', 'BULK'), ('O_M', 'O.M'), ('VA', 'VA')], max_length=10, verbose_name='نوع المنتج')),
                ('exp', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='EXP')),
                ('dom', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='DOM')),
                ('std', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='STD')),
                ('nc', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='NC')),
                ('defect_reason', models.CharField(blank=True, max_length=100, verbose_name='سبب العيب')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('car_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='رقم العربية')),
                ('car_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='وزن العربية')),
                ('shift_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sop_line_items', to='qc_report.shiftentry')),
            ],
            options={
                'ordering': ['product_type'],
            },
        ),
        migrations.AddConstraint(
            model_name='shiftentry',
            constraint=models.UniqueConstraint(fields=('unit', 'entry_date', 'shift'), name='unique_shift_per_unit_per_day'),
        ),
    ]
