# Generated by Django 6.1 on 2026-08-21 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc_report', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='soplineitem',
            name='cause',
            field=models.CharField(blank=True, max_length=200, verbose_name='Cause'),
        ),
        migrations.AddField(
            model_name='soplineitem',
            name='note',
            field=models.CharField(blank=True, max_length=200, verbose_name='Note'),
        ),
    ]
