# Generated by Django 6.1 on 2026-08-22 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc_report', '0002_soplineitem_cause_soplineitem_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dcpcolorgrading',
            name='category',
            field=models.CharField(choices=[('TOTAL', 'Total'), ('EX_SB', 'EX S.B'), ('DOM_SB', 'DOM S.B'), ('SB_WHITE', 'S.B White')], max_length=10, verbose_name='الفئة'),
        ),
    ]
