# Generated by Django 6.1 on 2026-08-22 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc_report', '0003_alter_dcpcolorgrading_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp_trucks', models.PositiveIntegerField(blank=True, null=True, verbose_name='EXP trucks')),
                ('dom_trucks', models.PositiveIntegerField(blank=True, null=True, verbose_name='DOM trucks')),
                ('std_trucks', models.PositiveIntegerField(blank=True, null=True, verbose_name='STD trucks')),
                ('nc_trucks', models.PositiveIntegerField(blank=True, null=True, verbose_name='NC trucks')),
                ('shift_entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_log', to='qc_report.shiftentry')),
            ],
            options={
                'verbose_name': 'BULK trucks log',
            },
        ),
    ]
