# Generated by Django 6.1 on 2026-08-22 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc_report', '0004_bulklog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dcprework',
            name='shift_entry',
        ),
        migrations.RemoveField(
            model_name='dcpsummary',
            name='shift_entry',
        ),
        migrations.RemoveField(
            model_name='dcpundertest',
            name='shift_entry',
        ),
        migrations.RemoveField(
            model_name='dcpwhitequality',
            name='shift_entry',
        ),
        migrations.CreateModel(
            name='DCPASRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='EXP')),
                ('dom', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='DOM')),
                ('sb_white', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='S.B White')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='Note')),
                ('shift_entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dcp_as', to='qc_report.shiftentry')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DCPBBRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('green', models.PositiveIntegerField(default=0, verbose_name='Green')),
                ('yellow', models.PositiveIntegerField(default=0, verbose_name='Yellow')),
                ('green_yellow', models.PositiveIntegerField(default=0, verbose_name='Green & Yellow')),
                ('blue', models.PositiveIntegerField(default=0, verbose_name='Blue')),
                ('white', models.PositiveIntegerField(default=0, verbose_name='White')),
                ('red', models.PositiveIntegerField(default=0, verbose_name='Red')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='Note')),
                ('shift_entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dcp_bb', to='qc_report.shiftentry')),
            ],
        ),
        migrations.CreateModel(
            name='DCPReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('WHITE', 'DCP White'), ('NC', 'DCP NC')], max_length=10, verbose_name='النوع')),
                ('name', models.CharField(max_length=50, verbose_name='السبب')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعل')),
            ],
            options={
                'ordering': ['category', 'order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('category', 'name'), name='uniq_dcp_reason_per_category')],
            },
        ),
        migrations.CreateModel(
            name='DCPReasonLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(default=0, verbose_name='الرقم')),
                ('reason', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='qc_report.dcpreason', verbose_name='السبب')),
                ('shift_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dcp_reason_lines', to='qc_report.shiftentry')),
            ],
            options={
                'ordering': ['reason__category', 'reason__order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DCPSBRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='EXP')),
                ('dom', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='DOM')),
                ('sb_white', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='S.B White')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='Note')),
                ('shift_entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dcp_sb', to='qc_report.shiftentry')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DCPTests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_test', models.PositiveIntegerField(default=0, verbose_name='اختبار معمل')),
                ('floor_test', models.PositiveIntegerField(default=0, verbose_name='اختبار أرضية')),
                ('shift_entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dcp_tests', to='qc_report.shiftentry')),
            ],
        ),
        migrations.DeleteModel(
            name='DCPColorGrading',
        ),
        migrations.DeleteModel(
            name='DCPRework',
        ),
        migrations.DeleteModel(
            name='DCPSummary',
        ),
        migrations.DeleteModel(
            name='DCPUnderTest',
        ),
        migrations.DeleteModel(
            name='DCPWhiteQuality',
        ),
    ]
