# Generated by Django 6.1 on 2026-08-22 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc_report', '0006_seed_dcp_reasons'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edited_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت التعديل')),
                ('data', models.JSONField(verbose_name='البيانات قبل التعديل')),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entry_revisions', to=settings.AUTH_USER_MODEL, verbose_name='عدّلها')),
                ('shift_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='qc_report.shiftentry')),
            ],
            options={
                'verbose_name': 'سجل تعديل إدخال',
                'verbose_name_plural': 'سجلات تعديل الإدخالات',
                'ordering': ['-edited_at'],
            },
        ),
    ]
