# Generated by Django 6.1 on 2026-08-22 15:25
# Edited: seed packing types + migrate old PA/SA data before removing old models.

import django.db.models.deletion
from django.db import migrations, models


def seed_and_migrate(apps, schema_editor):
    PackingType = apps.get_model("qc_report", "PackingType")
    PackingLineItem = apps.get_model("qc_report", "PackingLineItem")
    PALineItem = apps.get_model("qc_report", "PALineItem")
    SALineItem = apps.get_model("qc_report", "SALineItem")

    pa_types = {}
    for order, name in enumerate(
        ["JC 43%", "JC 61.5%", "Cube 43%", "Cube 61%"]
    ):
        t, _ = PackingType.objects.get_or_create(factory="PA", name=name)
        t.order = order
        t.save()
        pa_types[name] = t

    sa_type, _ = PackingType.objects.get_or_create(factory="SA", name="JC")
    sa_type.order = 0
    sa_type.save()

    field_map = [
        ("jc_43", "JC 43%"),
        ("jc_62", "JC 61.5%"),
        ("cube_43", "Cube 43%"),
        ("cube_61", "Cube 61%"),
    ]
    for row in PALineItem.objects.all():
        for field, name in field_map:
            PackingLineItem.objects.create(
                shift_entry=row.shift_entry,
                packing_type=pa_types[name],
                value=getattr(row, field) or 0,
            )
    for row in SALineItem.objects.all():
        PackingLineItem.objects.create(
            shift_entry=row.shift_entry,
            packing_type=sa_type,
            value=row.jc or 0,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('qc_report', '0007_entryrevision'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factory', models.CharField(choices=[('PA', 'PA'), ('SA', 'SA')], max_length=5, verbose_name='المصنع')),
                ('name', models.CharField(max_length=50, verbose_name='نوع التعبئة')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعل')),
            ],
            options={
                'ordering': ['factory', 'order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('factory', 'name'), name='uniq_packing_type_per_factory')],
            },
        ),
        migrations.CreateModel(
            name='PackingLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='القيمة')),
                ('shift_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packing_items', to='qc_report.shiftentry')),
                ('packing_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='qc_report.packingtype', verbose_name='نوع التعبئة')),
            ],
            options={
                'ordering': ['packing_type__factory', 'packing_type__order', 'id'],
            },
        ),
        migrations.RunPython(seed_and_migrate, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='salineitem',
            name='shift_entry',
        ),
        migrations.DeleteModel(
            name='PALineItem',
        ),
        migrations.DeleteModel(
            name='SALineItem',
        ),
        migrations.AddConstraint(
            model_name='packinglineitem',
            constraint=models.UniqueConstraint(fields=('shift_entry', 'packing_type'), name='uniq_packing_value_per_entry'),
        ),
    ]
