# Generated by Django 6.1 on 2026-08-22 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qc_report', '0008_packing_dynamic'),
    ]

    operations = [
        migrations.CreateModel(
            name='GCCColorRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('GREEN', 'GREEN'), ('YELLOW', 'YELLOW'), ('BLUE', 'BLUE'), ('WHITE', 'WHITE')], max_length=10, verbose_name='اللون')),
                ('bb', models.PositiveIntegerField(default=0, verbose_name='BB')),
                ('defect_reason', models.CharField(blank=True, max_length=200, verbose_name='Defect Reason')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='NOTES')),
                ('shift_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gcc_rows', to='qc_report.shiftentry')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='GCCSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sb', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='SB')),
                ('nc', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='NC')),
                ('shift_entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gcc_summary', to='qc_report.shiftentry')),
            ],
        ),
        migrations.DeleteModel(
            name='GCCLineItem',
        ),
        migrations.AddConstraint(
            model_name='gcccolorrow',
            constraint=models.UniqueConstraint(fields=('shift_entry', 'color'), name='uniq_gcc_color_per_entry'),
        ),
    ]
